spring.application.name=spring-data-jpa-best-practices
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Register our SQL interceptor to capture queries
spring.jpa.properties.hibernate.session_factory.statement_inspector=com.atypon.springdatajpabestpractices.util.SQLInterceptor
